// Banco de dados dos produtos

const data = [
  {
    id: 1,
    img: "./img/actions/ScorpionMK.png",
    imgAlt: "Estátua do personagem Scorpion do jogo Mortal Kombat 11",
    categoria: "Action Figure", 
    nameItem: "Scorpion",
    description:"Estátua do personagem Scorpion do jogo Mortal Kombat 11. Fabricante:Diamond em Escala: 1/8...",
    value: 700,
    addCart: "Adicionar ao carrinho",
    
  },
  {
    id: 2,
    img: "./img/actions/sektor.png",
    imgAlt: "Figura de ação do perosnagem Sektor do jogo Mortal Kombat",
    categoria: "Action Figure", 
    nameItem: "Sektor",
    description:"Figura de ação do perosnagem Sektor do jogo Mortal Kombat. Fabricante: Storm Collectibles em escala 1/12...",
    value: 664.50,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 3,
    img: "./img/actions/inosuke-min.png",
    imgAlt: "Estátua do personagem Inosuke Hashibira do anime Demon Slayer.",
    categoria: "Action Figure", 
    nameItem: "InosuKe Hashibira",
    description:"Estátua do personagem Inosuke Hashibira do anime Demon Slayer. Fabricante: Kotobukiya em escala: 1/7...",
    value: 1154,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 4,
    img: "./img/actions/ThommyShelb.png",
    imgAlt: "Estátua do personagem Thomas Shelby do seriado Peaky Blinders.",
    categoria: "Action Figure", 
    nameItem: "Thomas Shelby",
    description:"Estátua do personagem Thomas Shelby do seriado Peaky Blinders. Fabricante: Iron Studios em escala 1/10...",
    value: 1550,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 5,
    img: "./img/camisetas/camisa.jpeg",
    imgAlt: "camisa branca com os foras da lei Rick and Morty",
    categoria: "Camisetas", 
    nameItem: "Camisa Rick and Morty",
    description:'"Aahh Rick, não sei se é uma boa ideia". Uma excelente idéia é com certeza você levar essa linda camiseta...',
    value: 79.99,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 6,
    img: "./img/camisetas/camisa1.jpeg",
    imgAlt: "Camisa preta com uma estampa underground de um macaco",
    categoria: "Camisetas", 
    nameItem: "Camisa Monkey",
    description:"Você não pode deixar de conferir nosso mais novo mascote. Mistura de street, rap e arte pop, exclusivo e original...",
    value: 79.99,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 7,
    img: "./img/camisetas/camisa2.jpeg",
    imgAlt: "camisa roxa com estampa underground de um dragão ",
    categoria: "Camisetas", 
    nameItem: "Camisa Tattoo Dragão",
    description:"Tatuagens em pele de algodão. Nossas camisetas são feitas com os melhores tecidos do mercado...",
    value: 79.99,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 8,
    img: "./img/camisetas/camisa3.jpeg",
    imgAlt: "camisa branca com estampa da série Love Death + Robots",
    categoria: "Camisetas", 
    nameItem: "Camisa Love Death",
    description:"Baseado no aclamado Love Death + Robots. Nossas camisetas são feitas com os melhores tecidos do mercado...",
    value: 79.99,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 9,
    img: "./img/decoracao/GeekAstronauta.png",
    imgAlt: "Quadro com fundo rocho e uma ilustração de um Astronauta comendo Hamburguer",
    categoria: "Decoração", 
    nameItem: "Astronauta",
    description:"Deixe o seu ambiente preferido ainda mais lindo, com esse quadro de Astronauta...",
    value: 25.80,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 10,
    img: "./img/decoracao/GeekCoféCodeDev.png",
    imgAlt: "Quadro com fundo branco, um chicará de café feita em códigos",
    categoria: "Decoração", 
    nameItem: "Coffee Dev",
    description:"Requisito mínimo para ser um bom DEV, com certeza é um cafézinho, decore seu ambiente...",
    value: 50,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 11,
    img: "./img/decoracao/QuadroNaruto.png",
    imgAlt: "quadro com a ilustração do naruto divido no meio do rosto dele, o lado direito é o modo sabio e o lado esquerdo o modo kurama",
    categoria: "Decoração", 
    nameItem: "Naruto",
    description:"Deixe o seu ambiente preferido ainda mais lindo, com o quadro do Naruto Uzumaki...",
    value: 49.90,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 12,
    img: "./img/decoracao/QuadroRickMorty.png",
    imgAlt: "quadro com a ilustração do Rick and Morty em tons pretos, rochos e verdes.",
    categoria: "Decoração", 
    nameItem: "Rick and Morty",
    description:"Deixe o seu ambiente preferido ainda mais lindo, com esse quadro da dupla Rick and Morty...",
    value: 34.99,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 13,
    img: "./img/actions/batmanWhoLaughts.png",
    imgAlt: "Estátua do personagem Batman Que Ri dos quadrinhos da DC Comics",
    categoria: "Action Figure",
    nameItem: "Batman Who Laughs",
    description: "Estátua dos quadrinhos do Batman que Ri da DC Comics. Fabricante: Sideshow Collectibles, em escala 1/4...",
    value: 5550,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 14,
    img:"./img/camisetas/camisa5.jpeg",
    imgAlt:"Camiseta branca com estampa do pokemom Ice Squirtle",
    categoria:"Camisetas",
    nameItem:"Camiseta Ice Squirtle",
    description:"Nossa camisetas são feitas com os melhores tecidos do mercado e possuem acabamento e conforto...",
    value:79.99,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 15,
    img:"./img/decoracao/almofadaGamerJogando.png",
    imgAlt:"almofada preta e amarela, escrita não pertube, gamer jogando",
    categoria:"Decoração",
    nameItem:"Almofada Não pertube",
    description:"Para você jogar com muito mais conforto ou melhor, deixar bem claro que você está jogando...",
    value:55,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 16,
    img:"./img/actions/pikachu.png",
    imgAlt:"Figura de ação do personagem Pikachu do anime Pokemon",
    categoria:"Action Figure",
    nameItem:"Pikachu",
    description:"Figura de ação do personagem Pikachu do anime Pokemon. Fabricante: Bandai, em escala 1/10",
    value: 109,
    addCart: "Adicionar ao carrinho",
  },
  {
    id: 17,
    img:"./img/decoracao/BackEnd.png",
    imgAlt:"Almofada Preta escrito desenvolvedor Back End, com uma pequena ilustração de dois computadores no lado direito",
    categoria:"Decoração",
    nameItem:"Almofada DeV Back End",
    description:"Para você codar com muito mais conforto, nossas almofadas, são feitas com o melhor...",
    value:55,
    addCart: "Adicionar ao carrinho",
  },

];

